### ISSUE TITLE
Server crash (upon random pillager spawn?)

### ISSUE THREAD

**Issue by muon-rw** [IMB11/Armorful#20] opened 2024-06-05 02:33 UTC
Armorful-3.0.1+1.20.1
Minecraft 1.20.1
Fabric Loader 0.15.11

https://mclo.gs/r8lTfgd
https://mclo.gs/QrC2kfP

Potentially connected to Apoli?

Happened both times while idling in survival mode (hard difficulty) on a server environment for ~20 minutes. Local difficulty has to be high enough for armored pillagers to actually spawn.

Downgrading to Armorful 2.0.2 fixes the issue for now.

**Comment by justsaywhy2** [comment] 2024-09-01 17:38
Armorful-3.1.3+1.20.1
Minecraft 1.20.1
Fabric Loader 0.15.11

Same issue occured upon what I believe was Drowned spawning in.

**Comment by IMB11** [comment] 2024-12-24 20:15
Duplicate of #23

**Closed by IMB11** 2024-12-24 20:15 UTC
